# Generated by Django 4.1.7 on 2023-11-13 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familydhmsapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familyregister',
            old_name='passowrd',
            new_name='password',
        ),
    ]
