# Generated by Django 4.1.7 on 2023-11-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familydhmsapp', '0004_familydevicereg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familydevicereg',
            old_name='devicekind',
            new_name='devicetype',
        ),
        migrations.AddField(
            model_name='familydevicereg',
            name='devicelocation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
