# Generated by Django 4.1.7 on 2023-11-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familydhmsapp', '0005_rename_devicekind_familydevicereg_devicetype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familydevicereg',
            name='deviceuser',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
