# Generated by Django 4.1.7 on 2023-11-16 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familydhmsapp', '0006_familydevicereg_deviceuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='familydevicereg',
            name='devicemodel',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
