# Generated by Django 4.1.7 on 2023-11-21 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('familydhmsapp', '0007_familydevicereg_devicemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMemberReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memberfullname', models.CharField(blank=True, max_length=1500, null=True)),
                ('memberemail', models.EmailField(blank=True, max_length=1500, null=True)),
                ('memberid', models.CharField(blank=True, max_length=1500, null=True)),
                ('familyid', models.CharField(blank=True, max_length=1500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-edited_at', '-created_at'],
            },
        ),
    ]
