# Generated by Django 4.1.7 on 2023-11-21 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familydhmsapp', '0009_familydevicereg_devicestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='familydevicereg',
            name='userOSVersion',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='familydevicereg',
            name='userbrowser',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='familydevicereg',
            name='userbrowserversion',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
