# Generated by Django 4.1.7 on 2023-11-23 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('familydhmsapp', '0012_familydevicereg_deviceuserid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familydevicereg',
            name='deviceUserID',
        ),
        migrations.RemoveField(
            model_name='familydevicereg',
            name='deviceuseremail',
        ),
        migrations.RemoveField(
            model_name='familydevicereg',
            name='deviceuserfullname',
        ),
        migrations.AddField(
            model_name='familydevicereg',
            name='deviceUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='familydhmsapp.familymemberreg'),
        ),
    ]
