# Generated by Django 4.1.7 on 2023-12-08 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('familydhmsapp', '0015_familydevicereg_deviceimageone'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMaintainanceReq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintaindevicetype', models.CharField(default='None', max_length=1500)),
                ('maintaindevicebrand', models.CharField(blank=True, max_length=200, null=True)),
                ('maintaindeviceOS', models.CharField(blank=True, max_length=200, null=True)),
                ('maintaindevicemodel', models.CharField(blank=True, max_length=200, null=True)),
                ('maintaindevicename', models.CharField(blank=True, max_length=200, null=True)),
                ('maintaindevicemacaddress', models.CharField(blank=True, max_length=200, null=True)),
                ('maintaindeviceipaddress', models.CharField(blank=True, max_length=1500, null=True)),
                ('maintaindeviceid', models.CharField(blank=True, max_length=1500, null=True)),
                ('maintaindeviceuser', models.CharField(blank=True, max_length=1500, null=True)),
                ('maindeviceuserbrowser', models.CharField(blank=True, max_length=1500, null=True)),
                ('maindeviceuserbrowserversion', models.CharField(blank=True, max_length=1500, null=True)),
                ('maindeviceuserOSVersion', models.CharField(blank=True, max_length=1500, null=True)),
                ('maintaindeviceUserID', models.CharField(blank=True, default='None', max_length=1500, null=True)),
                ('maintaindeviceuseremail', models.CharField(blank=True, max_length=200, null=True)),
                ('maintaindeviceuserfullname', models.CharField(blank=True, max_length=200, null=True)),
                ('FamilyUniqueCode', models.CharField(blank=True, max_length=130, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-edited_at', '-created_at'],
            },
        ),
    ]
