# Generated by Django 4.1.7 on 2023-12-14 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('familydhmsapp', '0016_familymaintainancereq'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilySubAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userfullname', models.CharField(blank=True, default='None', max_length=1500, null=True)),
                ('useremail', models.CharField(blank=True, max_length=200, null=True)),
                ('FamilyUniqueCode', models.CharField(blank=True, max_length=130, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-edited_at', '-created_at'],
            },
        ),
    ]
