# Generated by Django 4.1.7 on 2023-12-15 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familydhmsapp', '0017_familysubadmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familymaintainancereq',
            name='maindeviceuserOSVersion',
        ),
        migrations.RemoveField(
            model_name='familymaintainancereq',
            name='maindeviceuserbrowser',
        ),
        migrations.RemoveField(
            model_name='familymaintainancereq',
            name='maindeviceuserbrowserversion',
        ),
        migrations.RemoveField(
            model_name='familymaintainancereq',
            name='maintaindeviceOS',
        ),
        migrations.RemoveField(
            model_name='familymaintainancereq',
            name='maintaindeviceUserID',
        ),
        migrations.RemoveField(
            model_name='familymaintainancereq',
            name='maintaindevicebrand',
        ),
        migrations.RemoveField(
            model_name='familymaintainancereq',
            name='maintaindeviceid',
        ),
        migrations.RemoveField(
            model_name='familymaintainancereq',
            name='maintaindeviceipaddress',
        ),
        migrations.RemoveField(
            model_name='familymaintainancereq',
            name='maintaindevicemacaddress',
        ),
        migrations.RemoveField(
            model_name='familymaintainancereq',
            name='maintaindevicemodel',
        ),
        migrations.RemoveField(
            model_name='familymaintainancereq',
            name='maintaindevicename',
        ),
        migrations.RemoveField(
            model_name='familymaintainancereq',
            name='maintaindevicetype',
        ),
        migrations.RemoveField(
            model_name='familymaintainancereq',
            name='maintaindeviceuser',
        ),
        migrations.RemoveField(
            model_name='familymaintainancereq',
            name='maintaindeviceuseremail',
        ),
        migrations.RemoveField(
            model_name='familymaintainancereq',
            name='maintaindeviceuserfullname',
        ),
        migrations.AddField(
            model_name='familymaintainancereq',
            name='maintainanceID',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='familymaintainancereq',
            name='maintainancedescription',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='familymaintainancereq',
            name='maintainancetitle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='familymaintainancereq',
            name='maintaindeviceID',
            field=models.CharField(blank=True, default='None', max_length=1500, null=True),
        ),
    ]
