# Generated by Django 4.2.7 on 2024-02-22 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familydhmsapp', '0018_remove_familymaintainancereq_maindeviceuserosversion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymemberreg',
            name='memberphone',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
