# Generated by Django 4.2.7 on 2024-02-28 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familydhmsapp', '0019_familymemberreg_memberphone'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymaintainancereq',
            name='MaintainStatus',
            field=models.CharField(blank=True, choices=[('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Ongoing', 'Ongoing'), ('Pending', 'Pending')], default='Pending', max_length=300, null=True),
        ),
    ]
