# Generated by Django 4.2.7 on 2024-02-28 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familydhmsapp', '0020_familymaintainancereq_maintainstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymaintainancereq',
            name='maintainanceRequester',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
