from django.urls import path
from . import views


urlpatterns = [
    path('nav/', views.NavBar, name="NavBar"),
    path('dashboard/', views.Dashboard, name="Dashboard"),
    path('devicesinventory/', views.DeviceInventory, name="DeviceInventory"),
    path('savedevice/', views.SaveDevice, name="SaveDevice"),
    path('staffmembers/', views.StaffMembers, name="StaffMembers"),
    path('reports/', views.Reports, name="Reports"),
    path('support/', views.Support, name="Support"),
    path('searchresult/', views.Searchresult, name="Searchresult"),
    path('maintainance/', views.Maintainance, name="Maintainance"),
    path('allmaintenancereqdelete/', views.AllMaintenanceDelete, name="AllMaintenanceDelete"),
    path('alldevicedelete/', views.AllDeviceDelete, name="AllDeviceDelete"),
    path('maintenancedetails/<str:name>/', views.MaintainanceDetails, name="MaintainanceDetails"),
    path('editmaintenancerequest/<str:name>/', views.EditMaintenenceRequest, name="EditMaintenenceRequest"),
    path('settings/', views.Settings, name="Settings"),
    path('staffdetails/<str:id>/', views.StaffDetails, name="StaffDetails"),
    path('registerStaff/<str:name>/', views.registerStaff, name="registerStaff"),
    path('editstaffdetails/<str:staffid>/', views.EditStaff, name="EditStaff"),
    path('editdevice/<str:deviceid>/', views.EditDevice, name="EditDevice"),
    path('scannetwork/', views.ScanNetwork, name="ScanNetwork"),
    path('logout/', views.Logout, name='Logout'),
    path('download_Sample_file/', views.downloadSampleFile, name="downloadSampleFile"),
    path('downloadsamplecsvheaders/', views.downloadSampleCSVHeaders, name="downloadSampleCSVHeaders"),
    path('downloadsamplecsv/', views.downloadSampleCSV, name="downloadSampleCSV"),
    path('deletedevice/<str:pk>/', views.DeleteDevice, name='DeleteDevice'),
    path('deletestaff/<str:pk>/', views.DeleteStaff, name='DeleteStaff'),
    path('editcompanydetails/<str:id>/', views.EditUserSignupDetails, name="EditUserSignupDetails"),
    path('updatedetails/<str:email>/<str:name>/', views.UpdateCompanyDetails, name="UpdateCompanyDetails"),
    path('profilepage/<str:pk>/', views.ProfilePage, name="ProfilePage"),
    path('uploadprofileimagepage/<str:pk>/', views.UploadProfileImg, name="UploadProfileImg"),
    # path('testpage/', views.TestPage, name="TestPage"),
    path('testpage/', views.AllInstalledApp, name="AllInstalledApp"),
    path('software/', views.AllInstalledSoftwares, name="AllInstalledSoftwares"),
    path('exportmaintenance/', views.ExportMaintenance, name="ExportMaintenance"),
    path('exportdevices/', views.ExportDevice, name="ExportDevice"),
    path('deletecomment/<str:pk>/<str:name>/', views.DeleteAddedComment, name="DeleteAddedComment"),
    path('viewdevicedetails/<str:name>/', views.ViewDeviceDetails, name="ViewDeviceDetails"),
    path('subadmin/', views.SubAdmin, name="SubAdmin"),
    path('deletesubadmin/<str:pk>/', views.DeletSubAdmin, name="DeletSubAdmin"),
    path('sample_staffad_file/', views.SampleFileForStaffAD, name="SampleFileForStaffAD"),
    path('errorpagevisist/', views.errorpagevisist, name="errorpagevisist"),
    # STREAM CALL URL SETUP
    path('callstaff/', views.Call_Staff, name="Call_Staff"),
]


