# Generated by Django 4.2 on 2024-06-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentdhms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdhmssignup',
            name='student_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentdhmssignup',
            name='student_phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
