# Generated by Django 4.2 on 2024-06-26 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentdhms', '0002_studentdhmssignup_student_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdhmssignup',
            name='user',
        ),
    ]
