# Generated by Django 4.2 on 2024-06-26 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentdhms', '0003_remove_studentdhmssignup_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdhmssignup',
            name='student_email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='studentdhmssignup',
            name='student_phone',
            field=models.IntegerField(blank=True, max_length=200, null=True),
        ),
    ]
