# Generated by Django 4.2 on 2024-06-26 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentdhms', '0004_alter_studentdhmssignup_student_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdhmssignup',
            name='student_phone',
        ),
        migrations.AlterField(
            model_name='studentdhmssignup',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='studentdhmssignup',
            name='edited_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='studentdhmssignup',
            name='student_email',
            field=models.EmailField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentdhmssignup',
            name='student_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentdhmssignup',
            name='student_password',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentdhmssignup',
            name='student_username',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
