# Generated by Django 4.2 on 2024-06-26 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentdhms', '0006_alter_studentdhmssignup_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdhmssignup',
            name='student_phone',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
