# Generated by Django 4.2 on 2024-07-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentdhms', '0010_password_reset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdhmssignup',
            name='student_username',
        ),
        migrations.AddField(
            model_name='studentdhmssignup',
            name='student_phone',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
