# Generated by Django 4.2 on 2024-08-01 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studentdhms', '0011_remove_studentdhmssignup_student_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubStudentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_student_name', models.CharField(max_length=200)),
                ('sub_student_email', models.EmailField(max_length=200)),
                ('sub_student_admin_email', models.EmailField(max_length=200)),
                ('sub_student_password', models.EmailField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-edited_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentDeviceReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_admin_email', models.EmailField(max_length=200)),
                ('device_name', models.CharField(max_length=200)),
                ('device_serial_number', models.CharField(max_length=200)),
                ('device_os', models.CharField(max_length=200)),
                ('student_user_email', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-edited_at', '-created_at'],
            },
        ),
    ]
