# Generated by Django 4.2 on 2024-08-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentdhms', '0012_substudentregistration_studentdevicereg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='substudentregistration',
            old_name='sub_student_email',
            new_name='sub_student_email_address',
        ),
        migrations.RenameField(
            model_name='substudentregistration',
            old_name='sub_student_name',
            new_name='sub_student_firstname',
        ),
        migrations.AddField(
            model_name='studentdevicereg',
            name='student_device_health',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='substudentregistration',
            name='sub_student_lastname',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='substudentregistration',
            name='sub_student_matric_number',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='substudentregistration',
            name='sub_student_phone_number',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='substudentregistration',
            name='sub_student_school_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentdevicereg',
            name='student_user_email',
            field=models.EmailField(max_length=200),
        ),
    ]
