# Generated by Django 5.1 on 2024-08-30 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentdhms', '0016_rename_student_id_studentmaintenancerequest_student_admin_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdhmssignup',
            name='accountActivationStatus',
            field=models.CharField(default=False, max_length=200),
        ),
        migrations.AddField(
            model_name='substudentregistration',
            name='accountActivationStatus',
            field=models.CharField(default=False, max_length=200),
        ),
    ]
