# Generated by Django 5.1 on 2024-08-31 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentdhms', '0017_studentdhmssignup_accountactivationstatus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTransactionPIN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_emailAddress', models.CharField(max_length=200)),
                ('student_id', models.CharField(max_length=200)),
                ('student_transaction_pin', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-edited_at', '-created_at'],
            },
        ),
    ]
