# Generated by Django 5.1 on 2024-08-31 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentdhms', '0019_rename_student_emailaddress_studenttransactionpin_student_email_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentdhmssignup',
            old_name='student_name',
            new_name='student_firstname',
        ),
        migrations.AddField(
            model_name='studentdhmssignup',
            name='student_lastname',
            field=models.CharField(default='lastname', max_length=200),
            preserve_default=False,
        ),
    ]
