# Generated by Django 5.1 on 2024-09-01 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentdhms', '0021_alter_studentdhmssignup_student_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdhmssignup',
            name='student_phone',
            field=models.IntegerField(),
        ),
    ]
