# Generated by Django 5.1 on 2024-09-02 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentdhms', '0024_paystackcustomerdata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PayStackCustomerData',
            new_name='PayStackCustomerAccountData',
        ),
    ]
