# Generated by Django 5.1 on 2024-09-02 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentdhms', '0025_rename_paystackcustomerdata_paystackcustomeraccountdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paystackcustomeraccountdata',
            old_name='customer_code',
            new_name='bank_account_creation_date',
        ),
        migrations.RenameField(
            model_name='paystackcustomeraccountdata',
            old_name='integration',
            new_name='bank_account_currency',
        ),
        migrations.RenameField(
            model_name='paystackcustomeraccountdata',
            old_name='paystack_id',
            new_name='bank_account_name',
        ),
        migrations.RenameField(
            model_name='paystackcustomeraccountdata',
            old_name='paystack_identifications',
            new_name='bank_account_number',
        ),
        migrations.RenameField(
            model_name='paystackcustomeraccountdata',
            old_name='paystack_identified',
            new_name='bank_customer_code',
        ),
        migrations.AddField(
            model_name='paystackcustomeraccountdata',
            name='bank_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paystackcustomeraccountdata',
            name='bank_name_slug',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
