# Generated by Django 5.1 on 2024-09-03 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentdhms', '0026_rename_customer_code_paystackcustomeraccountdata_bank_account_creation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paystackcustomeraccountdata',
            name='recipient_code',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
