# Generated by Django 5.1 on 2024-09-03 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentdhms', '0027_paystackcustomeraccountdata_recipient_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTransferRecipientCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_customer_code', models.CharField(max_length=200)),
                ('bank_account_number', models.CharField(max_length=200)),
                ('student_email_address', models.EmailField(max_length=200)),
                ('recipient_code', models.CharField(max_length=200)),
                ('recipient_id', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-edited_at', '-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='paystackcustomeraccountdata',
            name='recipient_code',
        ),
    ]
