# Generated by Django 5.1 on 2024-09-09 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentdhms', '0030_paystackcustomerwalletdetails_studenttransactions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paystackcustomerwalletdetails',
            name='bank_name_slug',
        ),
    ]
