# Generated by Django 5.1 on 2024-09-10 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentdhms', '0031_remove_paystackcustomerwalletdetails_bank_name_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='paystackcustomerwalletdetails',
            name='bank_name_slug',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
