# Generated by Django 5.1 on 2024-09-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentdhms', '0033_rename_studenttransactions_studentwallettransactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentwallettransactions',
            name='partnerAccountBank',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentwallettransactions',
            name='partnerAccountName',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentwallettransactions',
            name='partnerAccountNumber',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
