# Generated by Django 5.1 on 2024-09-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentdhms', '0036_registerpaystackcustomers'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerpaystackcustomers',
            name='customerCode',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registerpaystackcustomers',
            name='integration',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
