# Generated by Django 5.1 on 2024-09-11 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentdhms', '0038_studentwallettransactions_transactioncustomercode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentwallettransactions',
            name='transactionReference',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
