# Generated by Django 5.1 on 2024-09-12 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentdhms', '0041_remove_substudentregistration_sub_student_admin_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdevicereg',
            name='student_admin_email',
        ),
        migrations.AddField(
            model_name='studentdevicereg',
            name='student_admin_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
