# Generated by Django 5.1 on 2024-09-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentdhms', '0043_rename_studentemailaddress_verifyemailaddress_studentid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentID', models.CharField(blank=True, max_length=200, null=True)),
                ('transferAmount', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-edited_at', '-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='registerpaystackcustomers',
            name='StudentEmailAddress',
        ),
        migrations.AddField(
            model_name='paystackcustomerwalletdetails',
            name='student_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='registerpaystackcustomers',
            name='StudentID',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studenttransferrecipientcode',
            name='student_email_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
