# Generated by Django 5.1 on 2024-09-13 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentdhms', '0044_transferrequests_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferrequests',
            name='StudentID',
        ),
        migrations.AddField(
            model_name='transferrequests',
            name='receiverAccountNumber',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transferrequests',
            name='receiverBank',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transferrequests',
            name='receiverID',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transferrequests',
            name='senderStudentID',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transferrequests',
            name='transferFeedback',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transferrequests',
            name='transferID',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='transferrequests',
            name='transferNarration',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transferrequests',
            name='transferStatus',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Failed', 'Failed'), ('Approved', 'Approved')], default='Pending', max_length=300, null=True),
        ),
    ]
