# Generated by Django 5.1 on 2024-09-13 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentdhms', '0046_transferrequests_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentwallettransactions',
            name='StudentEmail',
        ),
        migrations.AddField(
            model_name='studentwallettransactions',
            name='StudentID',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
    ]
