# Generated by Django 5.1 on 2024-09-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentdhms', '0047_remove_studentwallettransactions_studentemail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studenttransferrecipientcode',
            name='student_email_address',
        ),
        migrations.RemoveField(
            model_name='studenttransferrecipientcode',
            name='student_email_id',
        ),
        migrations.AddField(
            model_name='studenttransferrecipientcode',
            name='student_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
