# Generated by Django 5.1 on 2024-09-13 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentdhms', '0048_remove_studenttransferrecipientcode_student_email_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paystackcustomerwalletdetails',
            name='student_email_address',
        ),
    ]
