# Generated by Django 5.1 on 2024-09-13 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentdhms', '0049_remove_paystackcustomerwalletdetails_student_email_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferrequests',
            name='receiverEmail',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
    ]
