# Generated by Django 5.1 on 2024-09-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentdhms', '0054_subscribeduser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdevicereg',
            name='student_user_email',
        ),
        migrations.AddField(
            model_name='studentdevicereg',
            name='student_user_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentmaintenancerequest',
            name='device_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
