# Generated by Django 5.1 on 2024-09-26 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentdhms', '0055_remove_studentdevicereg_student_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmaintenancerequest',
            name='maintenance_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Ongoing', 'Ongoing'), ('Declined', 'Declined'), ('Completed', 'Completed')], default='Pending', max_length=300),
        ),
    ]
