# Generated by Django 5.1 on 2024-09-30 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentdhms', '0057_studentwallettransactions_studentid'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentwallettransactions',
            name='transactionMethod',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='studentwallettransactions',
            name='transactionStatus',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Failed', 'Failed'), ('Approved', 'Approved')], default='Pending', max_length=300, null=True),
        ),
        migrations.DeleteModel(
            name='TransferRequests',
        ),
    ]
