# Generated by Django 5.1 on 2024-09-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentdhms', '0058_studentwallettransactions_transactionmethod_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentwallettransactions',
            old_name='partnerAccountBank',
            new_name='receiverAccountBank',
        ),
        migrations.RenameField(
            model_name='studentwallettransactions',
            old_name='partnerAccountName',
            new_name='receiverAccountName',
        ),
        migrations.RenameField(
            model_name='studentwallettransactions',
            old_name='partnerAccountNumber',
            new_name='receiverAccountNumber',
        ),
        migrations.AddField(
            model_name='studentwallettransactions',
            name='receiverCustomerID',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
