# Generated by Django 5.1 on 2024-09-30 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentdhms', '0059_rename_partneraccountbank_studentwallettransactions_receiveraccountbank_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentwallettransactions',
            old_name='StudentID',
            new_name='SenderStudentID',
        ),
        migrations.AddField(
            model_name='studentwallettransactions',
            name='receiverAccountStudentID',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
