# Generated by Django 5.1 on 2024-10-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentdhms', '0061_studentwallettransactions_senderaccountbank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdhmssignup',
            name='registeredMonth',
            field=models.CharField(blank=True, default=None, max_length=1500, null=True),
        ),
    ]
