# Generated by Django 5.1 on 2024-10-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentdhms', '0062_studentdhmssignup_registeredmonth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdhmssignup',
            name='registeredMonth',
        ),
        migrations.AddField(
            model_name='studentdevicereg',
            name='registeredMonth',
            field=models.CharField(blank=True, default=None, max_length=1500, null=True),
        ),
    ]
