# Generated by Django 5.1 on 2024-10-15 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentdhms', '0064_remove_studentdevicereg_registeredmonth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmaintenancerequest',
            name='techicianInCharge',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
    ]
