# Generated by Django 5.1 on 2024-10-30 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentdhms', '0065_studentmaintenancerequest_techicianincharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmaintenancerequest',
            name='student_requester_status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='studentmaintenancerequest',
            name='maintenance_issue',
            field=models.CharField(choices=[('Screen Repairs', 'Screen Repairs'), ('Battery Issues', 'Battery Issues'), ('Keyboard Issues', 'Keyboard Issues'), ('Motherboard Issues', 'Motherboard Issues'), ('Others', 'Others')], default='Other', max_length=300),
        ),
    ]
