# Generated by Django 5.1 on 2024-10-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentdhms', '0066_studentmaintenancerequest_student_requester_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmaintenancerequest',
            name='student_requester_status',
            field=models.CharField(default='StudentAdmin', max_length=200),
            preserve_default=False,
        ),
    ]
