# Generated by Django 5.1 on 2024-11-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentdhms', '0067_alter_studentmaintenancerequest_student_requester_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paystackcustomerwalletdetails',
            name='student_id',
            field=models.IntegerField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='studentdevicereg',
            name='student_admin_id',
            field=models.IntegerField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='studentdevicereg',
            name='student_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentmaintenancerequest',
            name='student_requester_id',
            field=models.IntegerField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='studenttransactionpin',
            name='student_id',
            field=models.IntegerField(blank=True, max_length=200, null=True),
        ),
    ]
