# Generated by Django 5.1 on 2024-11-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentdhms', '0068_alter_paystackcustomerwalletdetails_student_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paystackcustomerwalletdetails',
            name='student_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentdevicereg',
            name='student_admin_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentmaintenancerequest',
            name='student_admin_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentmaintenancerequest',
            name='student_requester_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studenttransactionpin',
            name='student_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='verifyemailaddress',
            name='studentID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='verifyphonenumber',
            name='studentID',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
