# Generated by Django 5.1 on 2024-11-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentdhms', '0069_alter_paystackcustomerwalletdetails_student_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substudentregistration',
            name='sub_student_admin_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
