# Generated by Django 4.2 on 2024-12-16 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstalledApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(blank=True, max_length=100, null=True)),
                ('installed_date', models.DateField(blank=True, null=True)),
                ('device_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
