# Generated by Django 4.2 on 2024-12-17 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devicescanapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='installedapplication',
            old_name='version',
            new_name='ip_address',
        ),
        migrations.AddField(
            model_name='installedapplication',
            name='mac_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
