# Generated by Django 4.2 on 2024-12-17 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devicescanapp', '0002_rename_version_installedapplication_ip_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=255)),
                ('operating_system', models.CharField(max_length=100)),
                ('cpu_usage', models.CharField(blank=True, max_length=100, null=True)),
                ('total_memory', models.CharField(blank=True, max_length=100, null=True)),
                ('used_memory', models.CharField(blank=True, max_length=100, null=True)),
                ('memory_usage', models.CharField(blank=True, max_length=100, null=True)),
                ('total_disk', models.CharField(blank=True, max_length=100, null=True)),
                ('used_disk', models.CharField(blank=True, max_length=100, null=True)),
                ('disk_usage', models.CharField(blank=True, max_length=100, null=True)),
                ('battery_percentage', models.CharField(blank=True, max_length=100, null=True)),
                ('is_charging', models.BooleanField(blank=True, null=True)),
                ('system_uptime', models.CharField(max_length=50)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.CharField(blank=True, max_length=100, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=255)),
                ('operating_system', models.CharField(max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=100, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
