# Generated by Django 4.0.5 on 2023-04-03 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userarea', '0002_registerstaff'),
    ]

    operations = [
        migrations.CreateModel(
            name='uploadedDeviceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=1500, null=True)),
                ('mainfile', models.FileField(null=True, upload_to='uploadedfiles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-edited_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffDataSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceuser', models.CharField(blank=True, max_length=200, null=True)),
                ('deviceuserphonenumber', models.CharField(blank=True, max_length=200, null=True)),
                ('deviceuseremail', models.CharField(blank=True, max_length=200, null=True)),
                ('deviceuserdateofresumption', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-edited_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceRegisterUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceip', models.CharField(blank=True, max_length=1500, null=True)),
                ('devicename', models.CharField(blank=True, max_length=1500, null=True)),
                ('devicemacaddress', models.CharField(blank=True, max_length=1500, null=True)),
                ('devicenetworkadaptercompany', models.CharField(blank=True, max_length=1500, null=True)),
                ('deviceuser', models.CharField(blank=True, max_length=200, null=True)),
                ('devicestatus', models.CharField(blank=True, max_length=1500, null=True)),
                ('deviceworkgroup', models.CharField(blank=True, max_length=1500, null=True)),
                ('deviceusedepartment', models.CharField(blank=True, max_length=1500, null=True)),
                ('deviceportnumber', models.CharField(blank=True, max_length=1500, null=True)),
                ('devicemultiplepacket', models.CharField(blank=True, max_length=1500, null=True)),
                ('index', models.CharField(blank=True, max_length=1500, null=True)),
                ('devicetype', models.CharField(blank=True, max_length=1500, null=True)),
                ('devicelocation', models.CharField(blank=True, max_length=1500, null=True)),
                ('devicebrand', models.CharField(blank=True, max_length=1500, null=True)),
                ('deviceos', models.CharField(blank=True, max_length=1500, null=True)),
                ('devicecostofpurchase', models.CharField(blank=True, max_length=1500, null=True)),
                ('deviceuseremail', models.CharField(blank=True, max_length=200, null=True)),
                ('deviceuserphonenumber', models.CharField(blank=True, max_length=200, null=True)),
                ('deviceuserdateofresumption', models.CharField(blank=True, max_length=200, null=True)),
                ('deviceworkingcondition', models.CharField(blank=True, max_length=1500, null=True)),
                ('deviceyearofpurchase', models.CharField(blank=True, max_length=1500, null=True)),
                ('devicedepreciationrate', models.CharField(blank=True, max_length=1500, null=True)),
                ('deviceid', models.CharField(blank=True, max_length=1500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-edited_at', '-created_at'],
            },
        ),
    ]
