# Generated by Django 4.0.5 on 2023-04-03 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userarea', '0003_uploadeddevicedata_staffdataset_deviceregisterupload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffdataset',
            old_name='deviceuserdateofresumption',
            new_name='devicelocation',
        ),
    ]
