# Generated by Django 4.0.5 on 2023-04-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userarea', '0004_rename_deviceuserdateofresumption_staffdataset_devicelocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceregisterupload',
            name='savetimedata',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
