# Generated by Django 4.2 on 2023-04-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userarea', '0006_devicecountperpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffdataset',
            name='staffrole',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
