# Generated by Django 4.2 on 2023-04-21 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userarea', '0007_staffdataset_staffrole'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedDevices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deletedDeviceName', models.CharField(blank=True, max_length=3, null=True)),
                ('deletedDeviceMAC_ID', models.CharField(blank=True, max_length=3, null=True)),
                ('deletedDeviceID', models.CharField(blank=True, max_length=3, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-edited_at', '-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='RegisterStaff',
        ),
        migrations.AddField(
            model_name='deviceregisterupload',
            name='staffUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userarea.staffdataset'),
        ),
    ]
