# Generated by Django 4.2 on 2023-04-22 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userarea', '0009_remove_deviceregisterupload_staffuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='MaintainDeviceCategory',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='MaintainDeviceIP',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='MaintainStatus',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='MaintainType',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
