# Generated by Django 4.2 on 2023-04-22 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userarea', '0010_maintenancerequest_maintaindevicecategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerequest',
            name='MaintainDeviceCategory',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='MaintainDeviceID',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='MaintainDeviceIP',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='MaintainDeviceMAC_ID',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='MaintainDeviceName',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='MaintainStatus',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='MaintainType',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
