# Generated by Django 4.2 on 2023-04-22 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userarea', '0011_alter_maintenancerequest_maintaindevicecategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='MaintainDeviceLocation',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='MaintainDeviceUser',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
