# Generated by Django 4.2 on 2023-04-24 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userarea', '0013_registerstaff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deviceregisterupload',
            old_name='deviceuser',
            new_name='deviceuserfirstname',
        ),
        migrations.RenameField(
            model_name='staffdataset',
            old_name='deviceuser',
            new_name='deviceuserfirstname',
        ),
        migrations.AddField(
            model_name='deviceregisterupload',
            name='deviceuserlastname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='staffdataset',
            name='deviceuserlastname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
