# Generated by Django 4.2 on 2023-04-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userarea', '0014_rename_deviceuser_deviceregisterupload_deviceuserfirstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffdataset',
            name='staffDevice',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
