# Generated by Django 4.2 on 2023-04-25 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userarea', '0015_staffdataset_staffdevice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegisterStaff',
        ),
        migrations.DeleteModel(
            name='SignupUser',
        ),
    ]
