# Generated by Django 4.2 on 2023-04-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userarea', '0017_staffdataset_staffdevicename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceregisterupload',
            name='weekNumberSaved',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
