# Generated by Django 4.2 on 2023-05-25 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userarea', '0018_deviceregisterupload_weeknumbersaved'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddedMaintenanceComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commenter', models.CharField(blank=True, max_length=300, null=True)),
                ('commentProper', models.CharField(blank=True, max_length=300, null=True)),
                ('CommentedMaintainDeviceName', models.CharField(blank=True, max_length=300, null=True)),
                ('CommentedMaintainDeviceUser', models.CharField(blank=True, max_length=300, null=True)),
                ('CommentedMaintainRequester', models.CharField(blank=True, max_length=300, null=True)),
                ('CommentedMaintainRequestID', models.CharField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-edited_at', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='MaintainRequestDescription',
            field=models.CharField(blank=True, max_length=30000, null=True),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='MaintainRequestID',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='MaintainRequester',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='deviceregisterupload',
            name='devicestatus',
            field=models.CharField(blank=True, choices=[('Working', 'Working'), ('Faulty', 'Faulty'), ('Critical', 'Critical')], default='Working', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='deviceregisterupload',
            name='deviceworkingcondition',
            field=models.CharField(blank=True, choices=[('Good', 'Good'), ('Bad', 'Bad')], default='Good', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='MaintainStatus',
            field=models.CharField(blank=True, choices=[('Completed', 'Completed'), ('Ongoing', 'Ongoing'), ('Canceled', 'Canceled')], default='Ongoing', max_length=300, null=True),
        ),
    ]
