# Generated by Django 4.2 on 2023-05-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userarea', '0018_deviceregisterupload_weeknumbersaved'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='MaintainRequestDescription',
            field=models.CharField(blank=True, max_length=30000, null=True),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='MaintainRequestID',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='MaintainRequester',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
