# Generated by Django 4.2 on 2023-05-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userarea', '0019_maintenancerequest_maintainrequestdescription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddedMaintenanceComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commenter', models.CharField(blank=True, max_length=300, null=True)),
                ('MaintainDeviceName', models.CharField(blank=True, max_length=300, null=True)),
                ('MaintainDeviceUser', models.CharField(blank=True, max_length=300, null=True)),
                ('MaintainRequester', models.CharField(blank=True, max_length=300, null=True)),
                ('MaintainRequestID', models.CharField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-edited_at', '-created_at'],
            },
        ),
    ]
