# Generated by Django 4.2 on 2023-05-30 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userarea', '0019_addedmaintenancecomments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicecountperpage',
            name='count',
            field=models.CharField(blank=True, default=4, max_length=3, null=True),
        ),
    ]
