# Generated by Django 4.2 on 2023-05-18 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userarea', '0020_addedmaintenancecomments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addedmaintenancecomments',
            old_name='MaintainDeviceName',
            new_name='CommentedMaintainDeviceName',
        ),
        migrations.RenameField(
            model_name='addedmaintenancecomments',
            old_name='MaintainDeviceUser',
            new_name='CommentedMaintainDeviceUser',
        ),
        migrations.RenameField(
            model_name='addedmaintenancecomments',
            old_name='MaintainRequestID',
            new_name='CommentedMaintainRequestID',
        ),
        migrations.RenameField(
            model_name='addedmaintenancecomments',
            old_name='MaintainRequester',
            new_name='CommentedMaintainRequester',
        ),
    ]
