# Generated by Django 4.2 on 2023-06-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userarea', '0021_rename_maintaindeviceuser_maintenancerequest_maintaindevicetype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicecountperpage',
            name='count',
            field=models.IntegerField(default=10),
        ),
    ]
