# Generated by Django 4.2 on 2023-05-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userarea', '0021_rename_maintaindevicename_addedmaintenancecomments_commentedmaintaindevicename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addedmaintenancecomments',
            name='commentProper',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
