# Generated by Django 4.2 on 2023-05-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userarea', '0022_addedmaintenancecomments_commentproper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerequest',
            name='MaintainStatus',
            field=models.CharField(blank=True, choices=[('Completed', 'Completed'), ('Ongoing', 'Ongoing'), ('Canceled', 'Canceled')], default='Ongoing', max_length=300, null=True),
        ),
    ]
