# Generated by Django 4.2 on 2023-06-07 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userarea', '0022_alter_devicecountperpage_count'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddedMaintenanceComments',
            new_name='AddedMaintenanceComment',
        ),
    ]
