# Generated by Django 4.2 on 2023-06-07 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userarea', '0023_rename_addedmaintenancecomments_addedmaintenancecomment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddedMaintenanceComment',
            new_name='AddedMaintenanceComments',
        ),
    ]
