# Generated by Django 4.2 on 2023-05-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userarea', '0024_alter_deviceregisterupload_devicestatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceregisterupload',
            name='devicestatus',
            field=models.CharField(blank=True, choices=[('Working', 'Working'), ('Faulty', 'Faulty'), ('Critical', 'Critical')], default='Working', max_length=300, null=True),
        ),
    ]
