# Generated by Django 4.2 on 2023-07-09 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userarea', '0025_alter_devicecountperpage_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceregisterupload',
            name='registeredMonth',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
