# Generated by Django 4.2 on 2023-08-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userarea', '0026_deviceregisterupload_registeredmonth'),
    ]

    operations = [
        migrations.AddField(
            model_name='deleteddevices',
            name='deletedDeviceBrand',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='deleteddevices',
            name='deletedDeviceCompanyUniqueCode',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='deleteddevices',
            name='deletedDeviceID',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='deleteddevices',
            name='deletedDeviceMAC_ID',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='deleteddevices',
            name='deletedDeviceName',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
