# Generated by Django 4.2 on 2023-05-27 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userarea', '0027_alter_deviceregisterupload_deviceworkingcondition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenancerequest',
            old_name='MaintainDeviceUser',
            new_name='MaintainDeviceUserFirstname',
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='MaintainDeviceUserLastname',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
