# Generated by Django 4.2 on 2023-05-28 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userarea', '0029_maintenancerequest_currentmonth'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='MaintainRequesterEmailAddress',
            field=models.EmailField(blank=True, max_length=300, null=True),
        ),
    ]
