# Generated by Django 4.2 on 2023-09-05 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userarea', '0029_subadminmodel_companyuniquecode_subadminmodel_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenancerequest',
            old_name='MaintainDeviceUserFirstname',
            new_name='MaintainDeviceUserID',
        ),
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='MaintainDeviceUserLastname',
        ),
    ]
