# Generated by Django 4.2 on 2023-09-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userarea', '0030_rename_maintaindeviceuserfirstname_maintenancerequest_maintaindeviceuserid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='MaintainDeviceUserFullName',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
