# Generated by Django 4.2 on 2023-09-05 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userarea', '0031_maintenancerequest_maintaindeviceuserfullname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='MaintainDeviceUserFullName',
        ),
    ]
