# Generated by Django 4.2 on 2023-06-01 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userarea', '0031_maintenancerequest_maintaindevicetype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicecountperpage',
            name='count',
            field=models.CharField(blank=True, default='10', max_length=10, null=True),
        ),
    ]
