# Generated by Django 4.2 on 2023-06-01 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userarea', '0032_alter_devicecountperpage_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='CompanyUniqueCode',
            field=models.EmailField(blank=True, max_length=300, null=True),
        ),
    ]
