# Generated by Django 4.2 on 2023-09-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userarea', '0032_remove_maintenancerequest_maintaindeviceuserfullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffdataset',
            name='staff_role',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('IT', 'IT'), ('HR', 'HR'), ('Admin', 'Admin'), ('Technician', 'Technician')], default='None', max_length=300, null=True),
        ),
    ]
