# Generated by Django 4.2 on 2023-09-06 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userarea', '0033_alter_staffdataset_staff_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='subadminmodel',
            name='subadmin_dept',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
