# Generated by Django 4.2 on 2023-06-02 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userarea', '0033_maintenancerequest_companyuniquecode'),
    ]

    operations = [
        migrations.AddField(
            model_name='addedmaintenancecomments',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
