# Generated by Django 4.2 on 2023-06-02 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userarea', '0034_addedmaintenancecomments_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='addedmaintenancecomments',
            name='commenterEmail',
            field=models.EmailField(blank=True, max_length=300, null=True),
        ),
    ]
