# Generated by Django 4.2 on 2023-09-21 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userarea', '0035_loginstatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginStatus',
        ),
    ]
