# Generated by Django 4.2 on 2023-06-02 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userarea', '0035_addedmaintenancecomments_commenteremail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addedmaintenancecomments',
            name='user',
        ),
        migrations.AddField(
            model_name='addedmaintenancecomments',
            name='commenterEmailAddress',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
