# Generated by Django 4.2 on 2023-06-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userarea', '0036_remove_addedmaintenancecomments_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addedmaintenancecomments',
            name='commenterEmail',
        ),
        migrations.AlterField(
            model_name='addedmaintenancecomments',
            name='commenterEmailAddress',
            field=models.EmailField(blank=True, max_length=300, null=True),
        ),
    ]
