# Generated by Django 4.2 on 2023-06-02 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userarea', '0037_remove_addedmaintenancecomments_commenteremail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceregisterupload',
            name='staffUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userarea.staffdataset'),
        ),
    ]
