# Generated by Django 4.1.7 on 2023-10-25 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userarea', '0037_alter_deviceregisterupload_deviceusedepartment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceregisterupload',
            name='devicetype',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Laptop', 'Laptop'), ('Desktop', 'Desktop'), ('Mobile Phone', 'Mobile Phone')], default='None', max_length=300, null=True),
        ),
    ]
