# Generated by Django 4.1.7 on 2023-10-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userarea', '0038_alter_deviceregisterupload_devicetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerequest',
            name='MaintainStatus',
            field=models.CharField(blank=True, choices=[('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Ongoing', 'Ongoing'), ('Pending', 'Pending')], default='Pending', max_length=300, null=True),
        ),
    ]
