# Generated by Django 4.2 on 2023-06-02 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userarea', '0038_deviceregisterupload_staffuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceregisterupload',
            name='CompanyUniqueCode',
            field=models.CharField(blank=True, max_length=130, null=True),
        ),
        migrations.AddField(
            model_name='staffdataset',
            name='CompanyUniqueCode',
            field=models.CharField(blank=True, max_length=130, null=True),
        ),
    ]
