# Generated by Django 4.2 on 2023-06-02 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userarea', '0039_deviceregisterupload_companyuniquecode_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffdataset',
            old_name='staffDevice',
            new_name='StaffID',
        ),
        migrations.RemoveField(
            model_name='staffdataset',
            name='staffDeviceName',
        ),
    ]
