# Generated by Django 4.2 on 2023-06-02 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userarea', '0040_rename_staffdevice_staffdataset_staffid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceregisterupload',
            name='staffUser',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
