# Generated by Django 4.1.7 on 2023-11-02 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userarea', '0041_rename_csv_file_staffadlist_staff_csv_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffadlist',
            name='approvalstatus',
            field=models.CharField(blank=True, choices=[('Under Review', 'Under Review'), ('Rejected', 'Rejected'), ('Approval', 'Approval')], default='Under Review', max_length=300, null=True),
        ),
    ]
