# Generated by Django 4.1.7 on 2023-11-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userarea', '0042_staffadlist_approvalstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffadlist',
            name='approvalstatus',
            field=models.CharField(blank=True, choices=[('Under Review', 'Under Review'), ('Rejected', 'Rejected'), ('Approved', 'Approved')], default='Under Review', max_length=300, null=True),
        ),
    ]
