# Generated by Django 4.2 on 2023-06-02 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userarea', '0042_rename_staffuser_deviceregisterupload_staffuserid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffdataset',
            old_name='deviceuseremail',
            new_name='staffuseremail',
        ),
        migrations.RenameField(
            model_name='staffdataset',
            old_name='deviceuserfirstname',
            new_name='staffuserfirstname',
        ),
        migrations.RenameField(
            model_name='staffdataset',
            old_name='deviceuserlastname',
            new_name='staffuserlastname',
        ),
        migrations.RenameField(
            model_name='staffdataset',
            old_name='deviceuserphonenumber',
            new_name='staffuserphonenumber',
        ),
    ]
