# Generated by Django 4.2 on 2023-06-02 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userarea', '0043_rename_deviceuseremail_staffdataset_staffuseremail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffdataset',
            old_name='staffDeviceStatus',
            new_name='staff_DeviceStatus',
        ),
        migrations.RenameField(
            model_name='staffdataset',
            old_name='staffrole',
            new_name='staff_email',
        ),
        migrations.RenameField(
            model_name='staffdataset',
            old_name='staffuseremail',
            new_name='staff_firstname',
        ),
        migrations.RenameField(
            model_name='staffdataset',
            old_name='staffuserfirstname',
            new_name='staff_lastname',
        ),
        migrations.RenameField(
            model_name='staffdataset',
            old_name='staffuserlastname',
            new_name='staff_phonenumber',
        ),
        migrations.RenameField(
            model_name='staffdataset',
            old_name='staffuserphonenumber',
            new_name='staff_role',
        ),
    ]
