# Generated by Django 4.1.7 on 2024-01-11 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userarea', '0043_alter_staffadlist_approvalstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyFaultyDevices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceID', models.CharField(blank=True, max_length=1500, null=True)),
                ('month', models.CharField(blank=True, max_length=1500, null=True)),
                ('year', models.CharField(blank=True, max_length=1500, null=True)),
                ('CompanyUniqueCode', models.CharField(blank=True, max_length=130, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-edited_at', '-created_at'],
            },
        ),
    ]
