# Generated by Django 5.0.1 on 2024-02-08 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userarea', '0044_companyfaultydevices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicecountperpage',
            name='count',
            field=models.CharField(default='5', max_length=10),
        ),
    ]
