# Generated by Django 4.2 on 2023-06-02 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userarea', '0044_rename_staffdevicestatus_staffdataset_staff_devicestatus_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffdataset',
            old_name='devicelocation',
            new_name='staff_location',
        ),
    ]
