# Generated by Django 4.2 on 2023-06-02 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userarea', '0045_rename_devicelocation_staffdataset_staff_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicecountperpage',
            name='count',
            field=models.CharField(default='10', max_length=10),
        ),
    ]
