# Generated by Django 4.2 on 2023-06-02 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userarea', '0046_alter_devicecountperpage_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffdataset',
            name='staff_DeviceStatus',
        ),
    ]
