# Generated by Django 5.1 on 2024-10-30 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userarea', '0046_maintenancerequest_maintainprioritystatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerequest',
            name='MaintainStatus',
            field=models.CharField(blank=True, choices=[('Completed', 'Completed'), ('Declined', 'Declined'), ('Ongoing', 'Ongoing'), ('Pending', 'Pending')], default='Pending', max_length=300, null=True),
        ),
    ]
