# Generated by Django 4.2 on 2023-06-03 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userarea', '0047_remove_staffdataset_staff_devicestatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceregisterupload',
            name='staffUserID',
            field=models.CharField(default='None', max_length=1500),
        ),
    ]
