# Generated by Django 5.0.1 on 2024-02-01 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhmsadminboard', '0002_superadminsmodel_adminaccesslevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='superadminsmodel',
            name='UniqueID',
            field=models.CharField(default=10, max_length=10),
        ),
    ]
