# Generated by Django 5.0.1 on 2024-02-01 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhmsadminboard', '0003_superadminsmodel_uniqueid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superadminsmodel',
            name='UniqueID',
            field=models.CharField(default=300, max_length=300),
        ),
        migrations.AlterField(
            model_name='superadminsmodel',
            name='email',
            field=models.EmailField(default=300, max_length=300),
        ),
        migrations.AlterField(
            model_name='superadminsmodel',
            name='firstname',
            field=models.CharField(default=300, max_length=300),
        ),
        migrations.AlterField(
            model_name='superadminsmodel',
            name='lastname',
            field=models.CharField(default=300, max_length=300),
        ),
        migrations.AlterField(
            model_name='superadminsmodel',
            name='password',
            field=models.CharField(default=300, max_length=300),
        ),
    ]
