# Generated by Django 4.2 on 2024-07-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhmsadminboard', '0005_alter_superadminsmodel_uniqueid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='technicianModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technicianEmail', models.EmailField(max_length=300)),
                ('TechnicianName', models.CharField(max_length=300)),
                ('UniqueID', models.CharField(max_length=300)),
                ('technicianAvailability', models.CharField(max_length=300)),
                ('technicianLocation', models.CharField(max_length=300)),
                ('password', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-edited_at', '-created_at'],
            },
        ),
    ]
