# Generated by Django 4.2 on 2024-07-23 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dhmsadminboard', '0006_technicianmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technicianmodel',
            name='UniqueID',
        ),
    ]
