# Generated by Django 4.2 on 2024-07-23 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dhmsadminboard', '0007_remove_technicianmodel_uniqueid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technicianmodel',
            old_name='TechnicianName',
            new_name='technicianName',
        ),
    ]
