# Generated by Django 4.2 on 2024-07-23 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dhmsadminboard', '0008_rename_technicianname_technicianmodel_technicianname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technicianmodel',
            old_name='password',
            new_name='technicianUniqueID',
        ),
    ]
