# Generated by Django 4.2 on 2024-07-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhmsadminboard', '0009_rename_password_technicianmodel_technicianuniqueid'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicianmodel',
            name='technicianPhoneNumber',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
