# Generated by Django 5.1 on 2024-10-03 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dhmsadminboard', '0010_technicianmodel_technicianphonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technicianmodel',
            name='technicianUniqueID',
        ),
    ]
