# Generated by Django 5.1 on 2024-10-10 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhmsadminboard', '0011_remove_technicianmodel_technicianuniqueid'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicianmodel',
            name='password',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
