# Generated by Django 5.1 on 2024-10-15 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhmsadminboard', '0012_technicianmodel_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicianmodel',
            name='technicianAvailability',
            field=models.CharField(choices=[('Ful_lTime', 'Full_Time'), ('Part_Time', 'Part_Time'), ('Not Available', 'Not Available'), ('Suspended', 'Suspended')], default='Full_Time', max_length=300),
        ),
    ]
