# Generated by Django 4.2 on 2024-12-16 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhmsadminboard', '0013_alter_technicianmodel_technicianavailability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicianmodel',
            name='technicianAvailability',
            field=models.CharField(choices=[('Full_Time', 'Full_Time'), ('Part_Time', 'Part_Time'), ('Not Available', 'Not Available'), ('Suspended', 'Suspended')], default='Full_Time', max_length=300),
        ),
    ]
