# Generated by Django 4.2 on 2023-04-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useronboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupform',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='signupform',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='signupform',
            name='country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='signupform',
            name='profilepicture',
            field=models.ImageField(blank=True, default='images/userprofilepic.png', null=True, upload_to='profileimages'),
        ),
        migrations.AlterField(
            model_name='signupform',
            name='password',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='signupform',
            name='repassword',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
