# Generated by Django 4.2 on 2023-04-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useronboard', '0003_userprofileimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signupform',
            name='profilepicture',
        ),
        migrations.AddField(
            model_name='userprofileimage',
            name='userReg',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
