# Generated by Django 4.2 on 2023-04-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useronboard', '0004_remove_signupform_profilepicture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileimage',
            name='profilepicture',
            field=models.ImageField(blank=True, default='profileimages/userprofilepic.png', null=True, upload_to='profileimages'),
        ),
    ]
