# Generated by Django 4.2 on 2023-04-27 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useronboard', '0007_alter_userprofileimage_profilepicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileimage',
            name='profilepicture',
            field=models.ImageField(blank=True, null=True, upload_to='profileimages'),
        ),
    ]
