# Generated by Django 4.2 on 2023-05-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useronboard', '0008_alter_userprofileimage_profilepicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileimage',
            name='profilepicture',
            field=models.ImageField(blank=True, null=True, upload_to='profileimages/'),
        ),
    ]
