# Generated by Django 4.2 on 2023-06-01 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useronboard', '0009_alter_userprofileimage_profilepicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupform',
            name='companyUniqueID',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
