# Generated by Django 4.2 on 2023-09-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useronboard', '0011_loginstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginstatus',
            name='status',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='loginstatus',
            name='email',
            field=models.EmailField(blank=True, max_length=300, null=True),
        ),
    ]
