# Generated by Django 4.2.7 on 2024-03-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useronboard', '0012_loginstatus_status_alter_loginstatus_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupform',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
