# Generated by Django 4.2 on 2024-07-09 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useronboard', '0013_alter_signupform_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userphonenumber', models.EmailField(blank=True, max_length=300, null=True)),
                ('useremail', models.EmailField(blank=True, max_length=300, null=True)),
                ('accountValidationCode', models.CharField(blank=True, max_length=300, null=True)),
                ('activationStatus', models.CharField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-edited_at', '-created_at'],
            },
        ),
    ]
