# Generated by Django 4.2 on 2024-07-16 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useronboard', '0014_accountvalidation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountvalidation',
            name='accountValidationCode',
        ),
        migrations.AddField(
            model_name='accountvalidation',
            name='max_otp_try',
            field=models.CharField(default=3, max_length=2),
        ),
        migrations.AddField(
            model_name='accountvalidation',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='accountvalidation',
            name='otp_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accountvalidation',
            name='otp_max_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
