# Generated by Django 4.2 on 2024-04-12 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aichat', '0002_airesponseprompt'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIChat_Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueId', models.CharField(max_length=1000)),
                ('companyID', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-edited_at', '-created_at'],
            },
        ),
        migrations.RenameField(
            model_name='airesponseprompt',
            old_name='chat_id',
            new_name='chatroomID',
        ),
        migrations.RenameField(
            model_name='chatprompts',
            old_name='chat_id',
            new_name='chatroomID',
        ),
    ]
