# Generated by Django 4.2 on 2024-04-13 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aichat', '0003_aichat_room_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatprompts',
            name='chatprompt',
        ),
        migrations.RemoveField(
            model_name='chatprompts',
            name='companyid',
        ),
        migrations.AddField(
            model_name='chatprompts',
            name='prompts',
            field=models.CharField(default=2, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatprompts',
            name='userID',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
